ZLC_ABI(3)
ZLC_MODULE(numpy_core)
ZLC_SOURCE("numpy_zy.c")

ZLC_HANDLE(Array, ZLC_DROP(zy_numpy_array_drop))

ZLC_FN(zeros, zy_numpy_zeros, optional<owned<Array>>, ZLC_PARAM(rows, i64), ZLC_PARAM(columns, i64), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(zeros_shape, zy_numpy_zeros_shape, optional<owned<Array>>, ZLC_PARAM(shape, Slice<usize>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(full, zy_numpy_full, optional<owned<Array>>, ZLC_PARAM(rows, i64), ZLC_PARAM(columns, i64), ZLC_PARAM(value, f64), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(full_shape, zy_numpy_full_shape, optional<owned<Array>>, ZLC_PARAM(shape, Slice<usize>), ZLC_PARAM(value, f64), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(from_slice, zy_numpy_from_slice, optional<owned<Array>>, ZLC_PARAM(rows, i64), ZLC_PARAM(columns, i64), ZLC_PARAM(values, Slice<f64>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(from_shape, zy_numpy_from_shape, optional<owned<Array>>, ZLC_PARAM(shape, Slice<usize>), ZLC_PARAM(values, Slice<f64>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(identity, zy_numpy_identity, optional<owned<Array>>, ZLC_PARAM(size, i64), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(rank, zy_numpy_rank, usize, ZLC_PARAM(array, borrowed<Array>))
ZLC_FN(dimension, zy_numpy_dimension, usize, ZLC_PARAM(array, borrowed<Array>), ZLC_PARAM(axis, usize))
ZLC_FN(rows, zy_numpy_rows, i64, ZLC_PARAM(array, borrowed<Array>))
ZLC_FN(columns, zy_numpy_columns, i64, ZLC_PARAM(array, borrowed<Array>))
ZLC_FN(length, zy_numpy_length, i64, ZLC_PARAM(array, borrowed<Array>))
ZLC_FN(get, zy_numpy_get, f64, ZLC_PARAM(array, borrowed<Array>), ZLC_PARAM(row, i64), ZLC_PARAM(column, i64))
ZLC_FN(set, zy_numpy_set, void, ZLC_PARAM(array, borrowed<Array>), ZLC_PARAM(row, i64), ZLC_PARAM(column, i64), ZLC_PARAM(value, f64))
ZLC_FN(get_at, zy_numpy_get_at, f64, ZLC_PARAM(array, borrowed<Array>), ZLC_PARAM(indices, Slice<usize>))
ZLC_FN(set_at, zy_numpy_set_at, void, ZLC_PARAM(array, borrowed<Array>), ZLC_PARAM(indices, Slice<usize>), ZLC_PARAM(value, f64))
ZLC_FN(sum, zy_numpy_sum, f64, ZLC_PARAM(array, borrowed<Array>))
ZLC_FN(minimum, zy_numpy_minimum, f64, ZLC_PARAM(array, borrowed<Array>))
ZLC_FN(maximum, zy_numpy_maximum, f64, ZLC_PARAM(array, borrowed<Array>))
ZLC_FN(copy, zy_numpy_copy, optional<owned<Array>>, ZLC_PARAM(array, borrowed<Array>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(reshape, zy_numpy_reshape, optional<owned<Array>>, ZLC_PARAM(array, borrowed<Array>), ZLC_PARAM(rows, i64), ZLC_PARAM(columns, i64), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(reshape_shape, zy_numpy_reshape_shape, optional<owned<Array>>, ZLC_PARAM(array, borrowed<Array>), ZLC_PARAM(shape, Slice<usize>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(transpose, zy_numpy_transpose, optional<owned<Array>>, ZLC_PARAM(array, borrowed<Array>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(add, zy_numpy_add, optional<owned<Array>>, ZLC_PARAM(left, borrowed<Array>), ZLC_PARAM(right, borrowed<Array>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(subtract, zy_numpy_subtract, optional<owned<Array>>, ZLC_PARAM(left, borrowed<Array>), ZLC_PARAM(right, borrowed<Array>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(multiply, zy_numpy_multiply, optional<owned<Array>>, ZLC_PARAM(left, borrowed<Array>), ZLC_PARAM(right, borrowed<Array>), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(scale, zy_numpy_scale, optional<owned<Array>>, ZLC_PARAM(array, borrowed<Array>), ZLC_PARAM(factor, f64), ZLC_FAIL(null, zy_numpy_last_error))
ZLC_FN(matmul, zy_numpy_matmul, optional<owned<Array>>, ZLC_PARAM(left, borrowed<Array>), ZLC_PARAM(right, borrowed<Array>), ZLC_FAIL(null, zy_numpy_last_error))
